# ---- Etapa de Construcción (Builder) ----
FROM node:20.18.1-alpine3.19 AS builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# ---- Etapa de Producción (Final) ----
FROM node:20.18.1-alpine3.19
WORKDIR /app
COPY package*.json ./
RUN npm install --omit=dev
COPY --from=builder /app/tsconfig.json ./
COPY --from=builder /app/tsconfig.build.json ./
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/src ./src
CMD ["npm", "run", "start:prod"]