# Etapa base
FROM node:22.17.0-alpine3.21

# Crear directorio de trabajo
WORKDIR /app

# Copiar archivos de dependencias
COPY package*.json ./

# Instalar dependencias
RUN npm install

# Copiar el resto del código
COPY . .

# Exponer el puerto de NestJS
EXPOSE 3000

# Ejecutar NestJS en modo desarrollo
CMD ["npm", "run", "start:dev"]
